spring:
  application:
    name: railwayAuthentication
  data:
      mongodb:
        uri: mongodb://localhost:27017/railwaydata
server:
  port: 8889
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    preferIpAddress: true